# Project: C_0512_Example
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = C_0512_AP.o C_0512_Type.o C_0512_Enum.o Homework_0512.o
LINKOBJ  = C_0512_AP.o C_0512_Type.o C_0512_Enum.o Homework_0512.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = C_0512_Example.exe
CXXFLAGS = $(CXXINCS) -std=c99
CFLAGS   = $(INCS) -std=c99
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

C_0512_AP.o: C_0512_AP.c
	$(CC) -c C_0512_AP.c -o C_0512_AP.o $(CFLAGS)

C_0512_Type.o: C_0512_Type.c
	$(CC) -c C_0512_Type.c -o C_0512_Type.o $(CFLAGS)

C_0512_Enum.o: C_0512_Enum.c
	$(CC) -c C_0512_Enum.c -o C_0512_Enum.o $(CFLAGS)

Homework_0512.o: Homework_0512.c
	$(CC) -c Homework_0512.c -o Homework_0512.o $(CFLAGS)
